# rga zed2-avia
common:
  img_topic: "/zed2/zed_node/left/image_rect_color"
  lid_topic: "/livox/lidar"
  imu_topic: "/livox/imu"
  #imu_topic: "/zed2/zed_node/imu/data"
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  extrinsic_T: [0.04165, 0.02326, -0.0284]
  extrinsic_R: [1, 0, 0, 
                0, 1, 0, 
                0, 0, 1]
  #extrinsic_T: [-0.005756, -0.040194,  0.051536] # zed2imu - avia 1
  #extrinsic_R: [0.999079, -0.009961, -0.041745,
  #              0.011016,  0.999623,  0.025137,
  #              0.041479, -0.025574,  0.998812]
  #extrinsic_T: [-0.009083, -0.048728, 0.054148] # zed2imu - avia 2
  #extrinsic_R: [0.999191, -0.006158, -0.039751,
  #              0.006574,  0.999925,  0.010345,
  #              0.039684, -0.010598,  0.999156]
  Rcl: [0.000695682, -0.999896, -0.0144194,
        -0.038241, 0.0143823, -0.999165,
        0.999268, 0.00124652, -0.038227]
  Pcl: [0.068314, -0.0530069, -0.0192628]

time_offset:
  imu_time_offset: 0.0
  #imu_time_offset: -0.10296341  # zed2imu - avia 1
  #imu_time_offset: -0.10057550  # zed2imu - avia 2
  #imu_time_offset: -0.04722450  # avia_imu - avia lidar 1
  #imu_time_offset: -0.04142456  # avia_imu - avia lidar 2
  #img_time_offset: 0.10296341   # zed2camera - avia 1
  img_time_offset: 0.0
  #img_time_offset: 0.10057550  # zed2camera - avia 1
  #img_time_offset: 0.10365848
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 1
  filter_en: true
  filter_size_surf: 0.2
  lidar_type: 1 # Livox Avia LiDAR
  scan_line: 6
  blind: 0.8
  

vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000 
  patch_size: 8
  patch_pyrimid_level: 4
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 0.5 # 0.2
  gyr_cov: 0.3 # 0.5
  b_acc_cov: 0.0001 # 0.1
  b_gyr_cov: 0.0001 # 0.1

lio:
  max_iterations: 1
  dept_err: 0.02
  beam_err: 0.05
  min_eigen_value: 0.0025 # 0.005
  sigma_num: 3
  voxel_size: 0.5
  max_layer: 3
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

ivox:
  grid_resolution: 0.5
  nearby_type: 0
  match_s: 300
  num_match_points: 5
  filter_size_map: 0.1
  noise_cov: 0.01

local_map:  
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: false
  gravity_align_en: false

publish:
  dense_map_en: false
  pub_effect_point_en: true 
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0
  pub_cut_num: 1

evo:
  seq_name: "rga"
  pose_output_en: false

pcd_save:
  pcd_save_en: false
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.1
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
